name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: unpmtu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - run: npm run verify

  publish-npm:
    needs: build
    runs-on: unpmtu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          NPM_CONFIG_TOKEN: ${{secrets.npm_token}}
